//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectManagerConnection : DbContext
    {
        public ProjectManagerConnection()
            : base("name=ProjectManagerConnection")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_parent_task> tbl_parent_task { get; set; }
        public virtual DbSet<tbl_project> tbl_project { get; set; }
        public virtual DbSet<tbl_task> tbl_task { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    
        public virtual ObjectResult<sp_AllProjects_Result> sp_AllProjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AllProjects_Result>("sp_AllProjects");
        }
    
        public virtual ObjectResult<sp_ViewAllProjectsWithNoOfTasks_Result> sp_ViewAllProjectsWithNoOfTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ViewAllProjectsWithNoOfTasks_Result>("sp_ViewAllProjectsWithNoOfTasks");
        }
    
        public virtual ObjectResult<ap_ViewAllProjectsWithTasks_Result> ap_ViewAllProjectsWithTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ap_ViewAllProjectsWithTasks_Result>("ap_ViewAllProjectsWithTasks");
        }
    
        public virtual ObjectResult<ap_ViewAllProjectsWithTasks_Result> ap_ViewAllProjectsWithTasks1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ap_ViewAllProjectsWithTasks_Result>("ap_ViewAllProjectsWithTasks1");
        }
    
        public virtual ObjectResult<SP_GETALLPROJECTSWITHTASK_Result> SP_GETALLPROJECTSWITHTASK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLPROJECTSWITHTASK_Result>("SP_GETALLPROJECTSWITHTASK");
        }
    
        public virtual ObjectResult<SP_GETALLPROJECTSWITHTASK1_Result> SP_GETALLPROJECTSWITHTASK1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLPROJECTSWITHTASK1_Result>("SP_GETALLPROJECTSWITHTASK1");
        }
    
        public virtual ObjectResult<SP_GETALLTASKS_Result> SP_GETALLTASKS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLTASKS_Result>("SP_GETALLTASKS");
        }
    
        public virtual ObjectResult<SP_GETALLTASKS1_Result> SP_GETALLTASKS1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLTASKS1_Result>("SP_GETALLTASKS1");
        }
    }
}
